//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_me.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("e_me.Core.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin user cannot be deleted!.
        /// </summary>
        public static string msgAdminUserCannotBeDeleted {
            get {
                return ResourceManager.GetString("msgAdminUserCannotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;New password&apos; should differ from the &apos;Old password&apos; !.
        /// </summary>
        public static string msgOldAndNewPasswordsShouldDiffer {
            get {
                return ResourceManager.GetString("msgOldAndNewPasswordsShouldDiffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The old password entered is incorrect!.
        /// </summary>
        public static string msgOldPasswordInputIncorrect {
            get {
                return ResourceManager.GetString("msgOldPasswordInputIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The old password is mandatory!.
        /// </summary>
        public static string msgOldPasswordMandatory {
            get {
                return ResourceManager.GetString("msgOldPasswordMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match!.
        /// </summary>
        public static string msgPasswordConfirmIncorrect {
            get {
                return ResourceManager.GetString("msgPasswordConfirmIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password confirmation is mandatory!.
        /// </summary>
        public static string msgPasswordConfirmMandatory {
            get {
                return ResourceManager.GetString("msgPasswordConfirmMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is mandatory!.
        /// </summary>
        public static string msgPasswordMandatory {
            get {
                return ResourceManager.GetString("msgPasswordMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found!.
        /// </summary>
        public static string msgUserNotFound {
            get {
                return ResourceManager.GetString("msgUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application administrator.
        /// </summary>
        public static string SecurityType_Administrator {
            get {
                return ResourceManager.GetString("SecurityType_Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application user.
        /// </summary>
        public static string SecurityType_RegularUser {
            get {
                return ResourceManager.GetString("SecurityType_RegularUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewer.
        /// </summary>
        public static string SecurityType_Viewer {
            get {
                return ResourceManager.GetString("SecurityType_Viewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string SessionStatus_Active {
            get {
                return ResourceManager.GetString("SessionStatus_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string SessionStatus_Inactive {
            get {
                return ResourceManager.GetString("SessionStatus_Inactive", resourceCulture);
            }
        }
    }
}
